/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-primary-container": "#000000",
        "on-surface": "#e2e2e2",
        "on-tertiary": "#1b1b1b",
        "on-secondary-container": "#e2e2e2",
        "on-background": "#e2e2e2",
        "inverse-surface": "#e2e2e2",
        "surface-container-lowest": "#0e0e0e",
        "outline-variant": "#474747",
        "surface-container": "#1f1f1f",
        "inverse-on-surface": "#303030",
        "surface": "#131313",
        "surface-tint": "#c6c6c6",
        "on-secondary-fixed-variant": "#3b3b3b",
        "secondary-fixed-dim": "#ababab",
        "surface-container-high": "#2a2a2a",
        "secondary-container": "#474747",
        "surface-bright": "#393939",
        "on-secondary-fixed": "#1b1b1b",
        "primary-fixed": "#5e5e5e",
        "background": "#131313",
        "on-primary-fixed-variant": "#e2e2e2",
        "on-secondary": "#1b1b1b",
        "surface-container-highest": "#353535",
        "on-surface-variant": "#c6c6c6",
        "surface-variant": "#353535",
        "outline": "#919191",
        "on-error-container": "#ffdad6",
        "secondary": "#c6c6c6",
        "error": "#ffb4ab",
        "primary-container": "#d4d4d4",
        "error-container": "#93000a",
        "secondary-fixed": "#c6c6c6",
        "surface-container-low": "#1b1b1b",
        "tertiary-fixed-dim": "#474747",
        "tertiary-fixed": "#5e5e5e",
        "primary-fixed-dim": "#474747",
        "tertiary": "#e2e2e2",
        "inverse-primary": "#5e5e5e",
        "tertiary-container": "#919191",
        "primary": "#ffffff",
        "on-tertiary-fixed": "#ffffff",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#e2e2e2",
        "on-primary": "#1b1b1b",
        "on-tertiary-container": "#000000",
        "on-primary-fixed": "#ffffff",
        "surface-dim": "#131313",
        "obsidian": "#0A0A0A",
        "momentum-gold": "#FFC800",
        "momentum-gold-bright": "#FFD700",
        "glass": "rgba(255,255,255,0.05)",
        "charcoal": "#1A1A1A",
        "slate-gray": "#888888",
        "border-glass": "rgba(255, 255, 255, 0.12)",
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "unit": "8px",
        "container-max": "1440px",
        "margin-desktop": "2rem",
        "section-gap": "3rem",
        "margin-mobile": "20px",
        "gutter": "24px"
      },
      "fontFamily": {
        "headline": ["Manrope", "sans-serif"],
        "display": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "headline-xl": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"]
      }
    }
  },
  plugins: [],
}
